function [fitresult, gof] = gaussianFit(X, Y, z, startingVec, make_plot)
%CREATEFIT(X,Y,Z)
%  Create a fit.
%
%  Data for 'gaussian' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Apr-2020 17:03:02


%% Fit: 'gaussian'.
[xData, yData, zData] = prepareSurfaceData( X, Y, z );

% Set up fittype and options.
ft = fittype( 'amplitude * exp(-((X-mu_x).^2/(2 * sigma^2) + (Y - mu_y).^2/ (2 * sigma^2)));', 'independent', {'X', 'Y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0  -78 38 0.0005];
opts.MaxIter = 10000;
opts.StartPoint = startingVec;
opts.Upper = [100  -75, 39.1 .005];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Plot fit with data.
if make_plot
    figure( 'Name', 'gaussian' );
    h = plot( fitresult, [xData, yData], zData );
    legend( h, 'gaussian', 'z vs. X, Y', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'X', 'Interpreter', 'none' );
    ylabel( 'Y', 'Interpreter', 'none' );
    zlabel( 'z', 'Interpreter', 'none' );
    grid on
    view( -88.5, 25.1 );
end


