function import_data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ERICWIFI22719 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ERICWIFI22719 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  EricWifi22719 = importfile("C:\Users\ARR87\Documents\GitHub\RowRender\RowdenRender\Content\Data\EricWifi-2-27-19.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Apr-2020 11:47:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Unixtime", "BSSID", "SignalstrengthdBm", "SSID", "Longitude", "Latitude", "GPSAccuracy", "APCapabilities", "Channel", "Frequency"];
opts.VariableTypes = ["double", "string", "double", "categorical", "double", "double", "double", "categorical", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["BSSID", "Channel"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["BSSID", "SSID", "APCapabilities", "Channel"], "EmptyFieldRule", "auto");

% Import the data
import_data = readtable(filename, opts);

end